### ISSUE TITLE
disable scrollwheel zoom in banner map

### ISSUE THREAD

**Issue by derekeder** [openoakland/oakland-soft-story-map#7]
This map is rad! 

![screen shot 2014-08-28 at 4 56 09 pm](https://cloud.githubusercontent.com/assets/919583/4083641/26a1dc8e-2efe-11e4-8028-537780d9b7a2.png)

However, the first thing I did when I hit the site was **scroll down** to see the rest of the home page and instead it zoomed the map out. I'd recommend disabling that in leaflet ([around here](https://github.com/openoakland/oakland-soft-story-map/blob/gh-pages/js/main.js#L207)) like so:

``` javascript
map = L.map('map', { scrollWheelZoom: false })
```

**Comment by spjika** [comment]
+1

**Comment by spjika** [comment]
fixed w pr #9

**Comment by derekeder** [comment]
nice!
